### ISSUE TITLE
Admin Dashboard: 

### ISSUE THREAD

**Issue by tthuyhuong** [Pick-and-buy/UGTS-FrontStage#58]
Khi đang ở brands và re-load lại trang thì cái button màu xanh nó lại nhảy lên Dashboard mặc dù vẫn ở trang brands
![90200942-b219-49f4-a27c-0a7cf615d846](https://github.com/user-attachments/assets/f9ffd735-4964-4146-bacf-76e2751790c5)

**Comment by nguyentienthanhe150825** [comment]
Nguyên nhân: do trạng thái activeMenu được khởi tạo mặc định là 'dashboard' mỗi khi component được render lại. Khi re-load trang, useState sẽ đặt lại activeMenu thành giá trị mặc định 'dashboard', thay vì giữ nguyên key tương ứng với đường dẫn URL hiện tại.

**Comment by nguyentienthanhe150825** [comment]
Giải pháp: Sử dụng useEffect để kiểm tra đường dẫn URL hiện tại và đặt lại activeMenu tương ứng mỗi khi component được render lại. Sử dụng useLocation từ react-router-dom để lấy đường dẫn URL hiện tại.
